/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"


void
mathprog_1(char *host, int x,char o, int y)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg;
	int  *result_2;
	intpair  multiply_1_arg;
	int  *result_3;
	int  cube_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATHPROG, MATHVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    if(o=='+'){
 
    
    add_1_arg.a=x;
    add_1_arg.b=y;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
    printf("Add Result: %d\n",*result_1);
    }
   
    }

    if(o=='x'){
    multiply_1_arg.a=x;
    multiply_1_arg.b=y;
	result_2 = multiply_1(&multiply_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
    printf("Multiply Result: %d\n",*result_2);
    }
    
    }

    if(o=='c'){    
    cube_1_arg=x;
	result_3 = cube_1(&cube_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}{
    printf("Cube Result: %d\n",*result_3);
    }
    
    }
    
    if(!(o=='x' || o=='+' || o=='c'))    
    {
 
    printf("Something Wrong!\nMult= *, Add= +, Cube= c !\n");
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host Int 1 Operator Int 2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	mathprog_1 (host, atoi(argv[2]),*argv[3],atoi(argv[4]));
exit (0);
}
